### ISSUE TITLE
how to create a new project

### ISSUE THREAD

**Issue by AshLeung** [SpinalHDL/SpinalTemplateSbt#5]
Hi, can u plz write a tutorial about how to create a spinalhdl project from scratch?

**Comment by AshLeung** [comment]
I write a script based on this template, it seems to be working now. But I have another question, how to specify the HDL generation directory instead of project root?

**Comment by Dolu1990** [comment]
Hi
Basicaly, personnaly, i always clone this repo, and incrementaly go from it. I didn't tried to fgo from scartch since years ^^

Also, about the generation directory, you can specify an option in the SpinalConfig : 
ex : 
SpinalConfig(targetDirectory = "hardware/netlist").generateVerilog(xxx)

You can also define new default SpinalConfig, see :
https://github.com/SpinalHDL/SaxonSoc/blob/24c8ba1bf4278cd3760c9edcca3a1c13672639aa/hardware/scala/saxon/package.scala

**Comment by AshLeung** [comment]
Thanks for your reply, I get it.
