### ISSUE TITLE
How to use SpinalHDL with ScalaIDE for Eclipse 4.7.0?

### ISSUE THREAD

**Issue by BLangOS** [SpinalHDL/SpinalTemplateSbt#8]
I just did download ScalaIDE for Eclipse 4.7.0 from [http://scala-ide.org/](http://scala-ide.org/).
Can I use it with SpinalHDL? The instructions in README.md of this project [see here](https://github.com/SpinalHDL/SpinalTemplateSbt#basics-with-eclipse-and-its-scala-plugin) do not work.
Thanks, Bernhard.

**Comment by Dolu1990** [comment]
Hi, 

If you revert those changes : 
https://github.com/SpinalHDL/SpinalTemplateSbt/commit/173bbb9bb8cbf70087339104f6ebced9321908dd

It might work.

I removed those because on some configuration it was making SBT to crash. Also the ScalaIde for eclipse seems to be abondonned (no updates since 3 years)

I suggest to use Intellij idea comunity edition instead :)

Regards
Charles

**Comment by piegamesde** [comment]
Eclipse still works, but the "ScalaIDE for Eclipse" indeed is dead by now. You can simply install the "Scala IDE" plugin to your up-to-date Eclipse installation from the market place.

**Comment by Dolu1990** [comment]
The issue was that the plugin was breaking sbt stuff on some environnements XD So i just dropped it.

**Comment by numero-744** [comment]
I think it can be closed
